version: "3.9"

services:
  db:
    image: "postgres:alpine"
    restart: always

    environment: 
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: cookbook-db

    ports:
      - "5432:5432"
